
#ifndef   _THREAD_JSON_WRITE_H_
#define   _THREAD_JSON_WRITE_H_

#include "io_thread.h"

namespace threads
{
  /**
  * A custom thread generated by gpc.pl
  **/
  class JSON_write : public io_thread
  {
  public:
    /**
     * Default constructor
     **/
    JSON_write (std::shared_ptr<boost::asio::serial_port> port, Containers & containers);
    
    /**
     * Destructor
     **/
    virtual ~JSON_write ();

    /**
      * Executes the main thread logic
      **/
    virtual void run (void);

  private:
    /**
      * Writes commands over serial
      */
    void write( json & data );

  };
} // end namespace threads

#endif // _THREAD_JSON_WRITE_H_
